# Kubernetes Deployment Template
# TODO: Fill in the missing values

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 2 # TODO: Set number of replicas
  selector:
    matchLabels:
      app: web-app # TODO: Match label
  template:
    metadata:
      labels:
        app: web-app # TODO: Pod label
    spec:
      containers:
        - name: nginx # TODO: Container name
          image: nginx:alpine # TODO: Image name (e.g., nginx:alpine)
          ports:
            - containerPort: 80 # TODO: Port number